name: Build and push Docker images to Dockerhub
on: push
jobs:
  cloudflare_dyndns:
    name: Build and push cloudflare-dyndns
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image to Dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          context: ./
          push: true
          tags: docker.io/timbordemann/cloudflare-dyndns:latest
