name: Build and push Docker images to Dockerhub
on: push
jobs:
  cloudflare_dyndns:
    name: Build and push cloudflare-dyndns
    runs-on: ubuntu-latest
    env:      
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: timbordemann/cloudflare-dyndns
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to Dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          plattforms: linux/amd64,linux/armv7l
          push: true
          tags: docker.io/timbordemann/cloudflare-dyndns:latest
